import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy — Ganit',
  description: 'Ganit privacy policy. How we collect, use, and protect your data.',
};

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-gray max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-gray-500">Last updated: April 11, 2026</p>

      {/* 1. Introduction */}
      <h2>1. Introduction</h2>
      <p>
        Ganit (&quot;we,&quot; &quot;our,&quot; or &quot;the App&quot;) is an educational math application designed
        for children and elderly users. We are committed to protecting the privacy of all our
        users, especially children. This Privacy Policy explains what information we collect, how
        we use it, and the choices you have.
      </p>

      {/* 2. Information Collected */}
      <h2>2. Information We Collect</h2>

      <h3>Account Information</h3>
      <ul>
        <li>Display name (chosen by the user)</li>
        <li>Parent/guardian email address (for users under 13)</li>
        <li>User group (child, elderly, or parent)</li>
        <li>Age (optional, used for COPPA compliance)</li>
      </ul>

      <h3>Learning Data</h3>
      <ul>
        <li>Quiz answers and accuracy scores</li>
        <li>Learning progress and skill levels</li>
        <li>Session duration and frequency</li>
        <li>Topic performance (addition, subtraction, multiplication, division)</li>
      </ul>

      <h3>On-Device Biometric Signals (iOS Only)</h3>
      <ul>
        <li><strong>Eye tracking:</strong> Gaze patterns during exercises (requires TrueDepth camera)</li>
        <li><strong>Facial analysis:</strong> Engagement and emotional indicators (requires TrueDepth camera)</li>
        <li><strong>Voice patterns:</strong> Speech rate, hesitation frequency, and confidence indicators</li>
        <li><strong>Touch patterns:</strong> Gesture speed, pressure sensitivity, and interaction timing</li>
      </ul>
      <p>
        <strong>Important:</strong> All biometric signals are processed entirely on your device.
        They are never transmitted to any server, never stored as raw data, and are encrypted
        with AES-256-GCM on the device. Only aggregate engagement scores derived from these
        signals are stored locally.
      </p>

      <h3>AI-Generated Content</h3>
      <ul>
        <li>Questions generated by the Gemini API based on grade level, topic, and accuracy data</li>
        <li>No personally identifiable information is sent to the AI service</li>
      </ul>

      {/* 3. How We Use It */}
      <h2>3. How We Use Your Information</h2>
      <ul>
        <li><strong>Adaptive learning:</strong> Adjusting question difficulty based on performance</li>
        <li><strong>Learning insights:</strong> Providing educational observations about learning patterns to parents</li>
        <li><strong>Gamification:</strong> Tracking points, coins, and skill levels to motivate learning</li>
        <li><strong>AR experiences:</strong> Enabling interactive math exercises using augmented reality</li>
      </ul>
      <p>We do not use your information for advertising, marketing to children, or selling data to third parties.</p>

      {/* 4. Children's Privacy (COPPA) */}
      <h2>4. Children&apos;s Privacy (COPPA Compliance)</h2>
      <p>
        We comply with the Children&apos;s Online Privacy Protection Act (COPPA). For users under 13:
      </p>
      <ul>
        <li>Verifiable parental consent is required before collecting any learning data or biometric signals</li>
        <li>Parents can review all data collected about their child from the Parent Dashboard</li>
        <li>Parents can delete all of their child&apos;s data at any time</li>
        <li>Parents can revoke consent, which will stop all data collection</li>
        <li>We do not display advertisements to children</li>
        <li>We do not sell, share, or rent children&apos;s personal information to any third party</li>
        <li>We do not condition a child&apos;s participation on disclosing more information than is reasonably necessary</li>
      </ul>

      {/* 5. Biometric Data */}
      <h2>5. Biometric Data</h2>
      <p>Ganit&apos;s iOS app collects the following biometric signals for educational purposes:</p>
      <ul>
        <li><strong>Eye tracking</strong> — analyzes gaze patterns to understand attention and focus</li>
        <li><strong>Facial analysis</strong> — detects engagement level and emotional state during learning</li>
        <li><strong>Voice patterns</strong> — measures speech rate, hesitations, and confidence when describing math problems</li>
        <li><strong>Touch patterns</strong> — analyzes gesture speed, pressure, and interaction timing</li>
      </ul>
      <p>All biometric data is:</p>
      <ul>
        <li>Processed entirely on-device using Apple&apos;s frameworks (ARKit, Speech, etc.)</li>
        <li>Encrypted with AES-256-GCM using a Keychain-stored master key</li>
        <li>Never transmitted to any external server</li>
        <li>Never stored as raw biometric data — only aggregate scores are retained</li>
        <li>Deleted immediately when the user deletes their account</li>
      </ul>

      {/* 6. Third-Party Services */}
      <h2>6. Third-Party Services</h2>

      <h3>Google Gemini API</h3>
      <p>
        We use the Google Gemini API to generate adaptive math questions. The only data sent to
        this service is:
      </p>
      <ul>
        <li>Grade level / difficulty tier</li>
        <li>Math topic (e.g., addition, fractions)</li>
        <li>Recent accuracy percentage</li>
      </ul>
      <p>
        No names, emails, biometric data, or any other personally identifiable information is
        sent to Google. If the Gemini API is unavailable, the app falls back to a local question
        generator.
      </p>

      <h3>Firebase (Web Version Only)</h3>
      <p>
        The web version of Ganit uses Firebase for authentication and data storage. Firebase is
        governed by Google&apos;s privacy policy. The iOS app does not use Firebase — all data is
        stored locally on the device.
      </p>

      {/* 7. Data Storage & Security */}
      <h2>7. Data Storage &amp; Security</h2>
      <h3>iOS App</h3>
      <ul>
        <li>All data is encrypted with AES-256-GCM</li>
        <li>Encryption master key is stored in the iOS Keychain</li>
        <li>Data is stored locally in encrypted UserDefaults</li>
        <li>Passwords are stored in the iOS Keychain (never in plain text)</li>
        <li>No data is transmitted to external servers (except Gemini API queries as described above)</li>
      </ul>
      <h3>Web App</h3>
      <ul>
        <li>Data is stored in Firebase Firestore with security rules</li>
        <li>Authentication is handled by Firebase Auth</li>
        <li>All connections use HTTPS/TLS encryption in transit</li>
      </ul>

      {/* 8. Data Retention */}
      <h2>8. Data Retention</h2>
      <p>
        We retain your data for as long as your account exists. Data is not automatically deleted
        after any time period. When you delete your account, all associated data is permanently
        removed immediately.
      </p>

      {/* 9. Your Rights */}
      <h2>9. Your Rights</h2>
      <p>You have the right to:</p>
      <ul>
        <li><strong>Access:</strong> View all data collected about you or your child via the Parent Dashboard</li>
        <li><strong>Deletion:</strong> Delete all data at any time through in-app account deletion</li>
        <li><strong>Portability:</strong> Request a copy of your data by contacting us</li>
        <li><strong>Consent withdrawal:</strong> Revoke parental consent at any time, stopping all data collection</li>
      </ul>

      {/* 10. Account Deletion */}
      <h2>10. Account Deletion</h2>
      <p>
        You can delete your account and all associated data directly within the app. See our{' '}
        <a href="/account-deletion" className="text-blue-600 hover:underline">
          Account Deletion page
        </a>{' '}
        for step-by-step instructions. Deletion is immediate and permanent.
      </p>

      {/* 11. Educational Disclaimer */}
      <h2>11. Educational Disclaimer</h2>
      <p>
        Ganit provides educational observations about learning patterns based on interaction data.
        These insights are <strong>not</strong> medical diagnoses, screenings, or assessments.
        They should not be used as a substitute for professional evaluation by qualified
        education or healthcare professionals. If you have concerns about your child&apos;s learning
        or development, please consult an appropriate professional.
      </p>

      {/* 12. Changes to Policy */}
      <h2>12. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. We will notify users of material
        changes by updating the &quot;Last updated&quot; date at the top of this page. For changes that
        affect children&apos;s data collection, we will seek renewed parental consent as required by
        COPPA.
      </p>

      {/* 13. Contact */}
      <h2>13. Contact Information</h2>
      <p>
        If you have questions about this Privacy Policy or our data practices, please contact us:
      </p>
      <ul>
        <li>
          Email:{' '}
          <a href="mailto:privacy@ganit.app" className="text-blue-600 hover:underline">
            privacy@ganit.app
          </a>
        </li>
      </ul>
    </article>
  );
}
